### ISSUE TITLE
Can't access default language with language-router enabled

### ISSUE THREAD

**Issue by dvoigt** [nimius/language-router#2]
My site consists of only one page and has four languages: default (English), German, Spanish and Dutch. Detection based on IP works fine; my German, Spanish and Dutch users are redirected from mydomain.tld to their specific languages. The only problem is that now I (with German IP) have no way to access the "/en" version anymore - I always get redirected to de-de.

For testing purposes, I'm only using IP based routing, no routing based on browser language and no fallback, I'll put those back in, later.

When I visit the site with the different language parameters, here are the expected results:

http://mydomain.tld -> IP detection -> redirect to German version
http://mydomain.tld/en/ -> no redirection
http://mydomain.tld/de-de/ -> no redirection
http://mydomain.tld/es-es/ -> no redirection
http://mydomain.tld/nl-nl/ -> no redirection

Here's what's happening:

http://mydomain.tld -> IP detection -> redirect to German version
*http://mydomain.tld/en/ -> redirect to German version*
http://mydomain.tld/de-de/ -> no redirection
http://mydomain.tld/es-es/ -> no redirection
http://mydomain.tld/nl-nl/ -> no redirection

Since English is the default language, mydomain.tld and mydomain.tld/en/ are being treated the same, which makes it impossible for a user to select the /en version.

Here's my language router TS:

> plugin.tx_languagerouter.settings {
    redirectCookie {       
        disregard = 1
        expirationInSeconds = 21600
    }
    
>    routes {
        // First priority: Route by country, detected from geoIP.
        1 {
            // This will return a 2-char country code.
            detection = country
            targets {
                // Redirect to the current page with L parameter set.
                GB.L = 0
                DE.L = 1
                CH.L = 1
                ES.L = 2
                NL.L = 3
            }
        }
}`

Here are my language settings:

> config {
        linkVars = L
        sys_language_uid = 0
        sys_language_overlay = 1
        sys_language_mode = content_fallback
        language = en
        country = GB
        defaultGetVars {
            L = 0
        }
        locale_all = en_GB.UTF-8
        htmlTag_setParams = lang="en" dir="ltr" class="no-js"
}
[globalVar = GP:L = 1]
        config {
                sys_language_uid = 1
                language = de
                country = DE
                locale_all = de_DE.UTF-8
                htmlTag_setParams = lang="de" dir="ltr" class="no-js"
        }
[global]
[globalVar = GP:L = 2]
        config {
                sys_language_uid = 2
                language = es
                country = ES
                locale_all = es_ES.UTF-8
                htmlTag_setParams = lang="es" dir="ltr" class="no-js"
        }
[global]
[globalVar = GP:L = 3]
        config {
                sys_language_uid = 3
                language = nl
                country = NL
                locale_all = nl_NL.UTF-8
                htmlTag_setParams = lang="nl" dir="ltr" class="no-js"
        }
[global]

And my realurl config: 

> <?php
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']=array (
  'mydomain.tld' => 
  array (
    'init' => 
    array (
      'emptyUrlReturnValue' => '/',
      'postVarSet_failureMode' => '',
    ),   
    'fileName' => 
    array (     
    'preVars' => 
    array (
      0 => 
      array (
        'GETvar' => 'L',
        'valueMap' => 
        array (
          'en' => '0',
          'de-de' => '1',
          'es-es' => '2',
          'nl-nl' => '3',
        ),
        'valueDefault' => 'en',
      ),
    ),
  ),
);

**Comment by dvoigt** [comment]
I might have found the solution myself. I have set plugin.tx_languagerouter.settings.redirectCookie.disregard = 0

Now I can visit the default language, as well, without being redirected. I'm not sure which way does what, since I have to set it to "not disregard" in order to "not redirect regardless", and not sure if a cookie is being set or not.

**Comment by pduersteler** [comment]
Have you tried removing `redirectCookie.disregard = 1`? Because that is IMHO the expected behavior:

```
// Redirect regardless if a redirect has already been made (which sets a cookie).
// This is especially useful if you have a visitable landing page that not just redirects.
```

With this, you enforce a redirect in any case, which will result to you being forced to your language.

**Comment by dvoigt** [comment]
That's it! Thank you! I did not understand that option, I guess. The // comment could be edited to include "With this, you enforce a redirect in any case, which will result to you being forced to your language."
